commitFormat: angular
title: "twitch-lichess-predictions release"
branch:
  master: release
changelog:
  printAll: false
release: 'github'
assets:
  - name: ./twitch-lichess-predictions
    compress: false
github:
  repo: "twitch-lichess-predictions"
  user: "ferencovonmatterhorn"